<?php

namespace AppBundle\Repository;

/**
 * HomeFlexBannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeFlexBannerRepository extends \Doctrine\ORM\EntityRepository
{
}
