<?php

namespace AppBundle\Repository;

/**
 * ProdCatJoinEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdCatJoinEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
