<?php

namespace AppBundle\Repository;

/**
 * ShoppingCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingCartRepository extends \Doctrine\ORM\EntityRepository
{
}
