<?php

namespace AppBundle\Repository;

/**
 * SizeForProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeForProductRepository extends \Doctrine\ORM\EntityRepository
{
}
