<?php

namespace AppBundle\Repository;

/**
 * SocialLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
