<?php

namespace AppBundle\Repository;

/**
 * TownshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownshipRepository extends \Doctrine\ORM\EntityRepository
{
}
