<?php

namespace AppBundle\Repository;

/**
 * UserPersonalDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPersonalDataRepository extends \Doctrine\ORM\EntityRepository
{
}
